### ISSUE TITLE
Unable to Add Options to field: VetsEZ Role

### ISSUE THREAD

**Issue by lgripka** [jason0848/ProjectTracking#10]
I am not able to add the 2 options to the field VetsEZ Role:

![image](https://user-images.githubusercontent.com/46937610/76899253-2b8f0400-6865-11ea-9521-5cc6f48a70d8.png)

![image](https://user-images.githubusercontent.com/46937610/76899318-482b3c00-6865-11ea-871f-acc03e66cd08.png)

**Comment by lgripka** [comment]
Same issue for field Competition Type:
![image](https://user-images.githubusercontent.com/46937610/76900822-136cb400-6868-11ea-8ef3-8303434c02c9.png)

**Comment by lgripka** [comment]
Same issue for Issuing Office: 
![image](https://user-images.githubusercontent.com/46937610/76900855-23849380-6868-11ea-87f4-59ac0661302f.png)

**Comment by lgripka** [comment]
Same issue for Capture Status:
![image](https://user-images.githubusercontent.com/46937610/76900889-313a1900-6868-11ea-96b1-a25996f97ca0.png)

**Comment by lgripka** [comment]
Same issue for No Bid Reason:
![image](https://user-images.githubusercontent.com/46937610/76900916-3dbe7180-6868-11ea-9300-c9f55845bd89.png)

**Comment by lgripka** [comment]
Same issue for field Tier.

![image](https://user-images.githubusercontent.com/46937610/76900933-4747d980-6868-11ea-8e90-527e8647d0e9.png)

**Comment by lgripka** [comment]
Same issue for Period of Performance (PoP)
![image](https://user-images.githubusercontent.com/46937610/76900985-5cbd0380-6868-11ea-9f84-4be95eb9c25e.png)

**Comment by jason0848** [comment]
Complete

**Comment by lgripka** [comment]
This is still broken for VetsEZ Role when I entered Prime and hit save:
![image](https://user-images.githubusercontent.com/46937610/77011193-4f237e80-6939-11ea-9dcd-6a70adba68ca.png)
